services:
  db:
    image: postgres:17
    restart: always
    container_name: event_management
    ports:
      - 5432:5432

    environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: 454675
       POSTGRES_DB: event-management
      
    volumes:
      - db_data:/var/lib/postgresql/db_data

volumes:
 db_data:
