CREATE TABLE "users" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" varchar(100) NOT NULL,
	"username" varchar(50) NOT NULL,
	"email" varchar(250) NOT NULL,
	"password" varchar(255) NOT NULL,
	"role" "user_role" DEFAULT 'student' NOT NULL,
	"roll_number" varchar(50) NOT NULL,
	"branch" varchar(50) NOT NULL,
	"year" integer NOT NULL,
	"phone" varchar(15) NOT NULL,
	"profile_image_url" text,
	"verify_otp" varchar(10),
	"verify_otp_expired_at" timestamp with time zone,
	"is_account_verified" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "users_username_unique" UNIQUE("username"),
	CONSTRAINT "users_email_unique" UNIQUE("email"),
	CONSTRAINT "users_roll_number_unique" UNIQUE("roll_number")
);
